disabled_rules:
- force_cast
- line_length
- trailing_whitespace
- todo
- redundant_discardable_let
- discarded_notification_center_observer
- identifier_name
- force_try

excluded:
- Pods
- IVPNClient/Utilities/Pinger/PingManager

function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 6
    error: 8
type_body_length:
    warning: 400
    error: 500
file_length:
    warning: 1000
    error: 1500
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode"